#!/usr/bin/env python3
"""Generate docs/architecture-case-matrix.md: the Stage-1 common-envelope case matrix.

Emits (1) the full 16-case classification table, (2) the ranked-results table (rank-eligible
cases only), (3) the sensitivity appendix (non-ranked cases actually evaluated with explicit
parametric inputs), (4) the count summary, and (5) a modeled-component-mass table for the
reference cases. Requires CoolProp. Run: ``python scripts/generate_architecture_matrix.py``.
"""

from __future__ import annotations

from pathlib import Path

from orbital_thermal import architecture_cases as ac

# uncited parametric conductivity bounds for the sensitivity appendix (labelled sensitivity,
# never ranked): APG in-plane, diamond-composite. These are NOT sourced ranked values.
_PARAMETRIC_K = {"apg": 1500.0, "diamond_composite": 1000.0}


def _reasons(case: ac.CaseResult) -> str:
    return "; ".join(r.value for r in case.reason_codes)


def main() -> None:
    env = ac.Stage1Envelope()
    results = ac.build_case_matrix(env)
    summ = ac.matrix_summary(results)

    lines: list[str] = []
    w = lines.append
    w("> **Generated by `scripts/generate_architecture_matrix.py`.** Working verification "
      "record; not a validated result. All inputs are Stage-1 **design variables** under one "
      "declared common operating envelope -- **not** an AI1 / Starcloud / Suncatcher comparison.")
    w("")
    w("# Stage-1 common-envelope architecture case matrix (B5)")
    w("")
    w("## Common operating envelope (all design variables)")
    w("")
    w(f"- heat load `Q_compute` = {env.q_compute_W:.0f} W; effective sink = "
      f"{env.sink_temperature_K:.0f} K (inherited Phase A shielded boundary); emissivity = "
      f"{env.emissivity}; contract = {env.contract.value} (A_emit = {env.area_fraction:g}*A_plan).")
    w(f"- mass flow = {env.mass_flow_kg_s} kg/s; tube D = {env.tube_diameter_m*1e3:.1f} mm, "
      f"L = {env.loop_length_m} m; radiator area = {env.radiator_area_m2} m^2 (Mode T); "
      f"low-side pressure = {env.low_side_pressure_Pa/1e5:.0f} bar; junction limit = "
      f"{env.t_junction_max_K:.2f} K.")
    w(f"- solid path: source r = {env.source_radius_m*1e3:.0f} mm, plate r = "
      f"{env.plate_radius_m*1e3:.0f} mm, thickness = {env.thickness_m*1e3:.0f} mm, contact "
      f"conductance = {env.contact_conductance_W_m2K:.0e} W/m^2K (cited: {env.contact_source}).")
    w("")
    w("## 1. Full case classification (all 16 combinations)")
    w("")
    w("| Coolant | Material | Contract | Classification | Reason code(s) |")
    w("|---|---|---|---|---|")
    for r in results:
        w(f"| {r.coolant} | {r.material} | {r.contract} | **{r.classification.value}** | "
          f"{_reasons(r)} |")
    w("")
    w("## 2. Count summary")
    w("")
    w(f"- **{summ['total']} total** combinations")
    w(f"- **{summ['rank_eligible']} rank-eligible** (enter ranked outputs)")
    w(f"- **{summ['non_ranked']} non-ranked**: {summ['sensitivity_only']} sensitivity-only "
      f"(CO2 near-critical), {summ['source_required']} source-required "
      f"(PGW composition; anisotropic APG/diamond), {summ['unsupported']} unsupported, "
      f"{summ['rejected']} rejected.")
    w("")
    w("## 3. Ranked results (rank-eligible cases only)")
    w("")
    w("Ranked **only** against this common Stage-1 envelope. No published-architecture claim.")
    w("")
    w("| Coolant | Material | T_j (K) | T_rad (K) | Reynolds | pump P_elec (W) | dP (kPa) | "
      "modeled mass (kg) |")
    w("|---|---|---:|---:|---:|---:|---:|---:|")
    for r in ac.ranked_cases(results):
        c = r.coupled
        w(f"| {r.coolant} | {r.material} | {c.T_j_K:.1f} | {c.T_rad_K:.1f} | {c.reynolds:.0f} | "
          f"{c.pump.electrical_power_W:.2f} | {c.pressure_drop_Pa/1e3:.1f} | "
          f"{r.mass.total_modeled_kg:.3f} |")
    w("")
    w("## 4. Sensitivity appendix (non-ranked cases evaluated with explicit parametric inputs)")
    w("")
    w("Anisotropic solids run **only** with an explicitly supplied, **uncited parametric** "
      "conductivity; they are labelled sensitivity, are **never** rank-eligible, and are "
      "**never** averaged into ranked conclusions. CO2/PGW are not evaluable (no rank-eligible "
      "property backend) and remain classification-only.")
    w("")
    w("| Coolant | Material | parametric k (W/mK) | classification | T_j (K) | rank-eligible |")
    w("|---|---|---:|---|---:|---|")
    for coolant in ("ammonia", "water"):
        for material, k in _PARAMETRIC_K.items():
            s = ac.evaluate_case(env, coolant, material, parametric_conductivity_W_mK=k,
                                 parametric_note="uncited parametric sensitivity bound")
            tj = f"{s.coupled.T_j_K:.1f}" if s.coupled else "n/a"
            w(f"| {coolant} | {material} | {k:.0f} (uncited) | {s.classification.value} | {tj} | "
              f"**no** |")
    w("")
    w("## 5. Modeled component mass (reference cases; incomplete Stage-1 accounting, 4.8a)")
    w("")
    w("Only components with a declared geometry/material basis are included. This is **not** "
      "total thermal-system, launch, or flight-qualified mass.")
    w("")
    ref = ac.evaluate_case(env, "ammonia", "aluminum")
    w("Example breakdown (ammonia x aluminum):")
    w("")
    w("| Component | mass (kg) | basis | included | completeness |")
    w("|---|---:|---|---|---|")
    for comp in ref.mass.components:
        mass = f"{comp.mass_kg:.4f}" if comp.mass_kg is not None else "-"
        w(f"| {comp.name} | {mass} | {comp.basis} | {comp.included} | {comp.completeness} |")
    w(f"| **total modeled** | **{ref.mass.total_modeled_kg:.3f}** | | | "
      "modeled component mass (incomplete) |")
    w("")
    w(f"**Excluded (not modeled at Stage-1):** {', '.join(ref.mass.excluded_components)}.")
    w("")

    out = Path("docs/architecture-case-matrix.md")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
