#!/usr/bin/env python3
"""Generate the B6 trade-study artifacts over the declared Stage-1 grid.

Writes:
- ``docs/trade-study-points.csv`` -- the **machine-readable** point table (every point, every
  objective, feasibility, category, reason codes, per-front Pareto membership).
- ``docs/trade-study.md`` -- a human-readable summary (grid metadata, count summary, the six
  Pareto fronts with axes / sense / dominating assumption / members / degenerate records).

Figures are **deferred to B7**; this milestone emits plot-ready data only. Requires CoolProp.
Run: ``python scripts/generate_trade_study.py``.
"""

from __future__ import annotations

import warnings
from pathlib import Path

from orbital_thermal import trade_study as ts


def main() -> None:
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")  # transitional-flow warnings are captured as reason codes
        res = ts.build_trade_study()
    meta = res.grid_metadata
    summ = res.summary()

    # 1) machine-readable CSV
    csv_path = Path("docs/trade-study-points.csv")
    csv_path.write_text("\n".join(ts.to_csv_rows(res)) + "\n")

    # 2) human-readable summary
    lines: list[str] = []
    w = lines.append
    w("> **Generated by `scripts/generate_trade_study.py`.** Working verification record; not a "
      "validated result. The **engine** carries executable verification (c); the physics "
      "**inherits** B1-B5 and is not re-validated here. **Figures are deferred to B7** -- this "
      "page + [`trade-study-points.csv`](trade-study-points.csv) are the plot-ready data.")
    w("")
    w("# Stage-1 trade-study Pareto data (B6)")
    w("")
    w("## Declared design grid (modest; recorded for reproduction)")
    w("")
    w(f"- heat load Q (W): {meta['heat_load_W']}")
    w(f"- mass flow m_dot (kg/s): {meta['mass_flow_kg_s']}")
    w(f"- radiator area A_plan (m^2): {meta['radiator_area_m2']}")
    w(f"- low-side pressure P_lo (Pa): {meta['low_side_pressure_Pa']}")
    w(f"- grid points per case: {meta['grid_points_per_case']}; rank-eligible cases: "
      f"{meta['n_cases']}; model version: {meta['model_version']}.")
    w("")
    w("Fixed (declared Stage-1 assumptions, not swept): tube diameter, loop length, cold-plate "
      "and radiator wetted geometry, contact resistance, material geometry, junction-limit "
      "threshold. `T_j <= T_j_max` is a **filter** (infeasible points reported, never dropped).")
    w("")
    w("## Count summary")
    w("")
    w(f"- total points: **{summ['total_points']}** ({meta['n_cases']} cases x "
      f"{meta['grid_points_per_case']} grid points)")
    w(f"- feasible (ranked): **{summ['feasible_ranked']}**; gate-rejected (infeasible, "
      f"reported with reasons): **{summ['gate_rejected']}**; **nonconverged** (solver did "
      f"not converge -- NOT evidence of physical infeasibility): **{summ['nonconverged']}**")
    w(f"- Pareto fronts: **{summ['fronts']}**; degenerate/empty: **{summ['degenerate_fronts']}**")
    w("")
    # infeasible reason breakdown
    reason_counts: dict[str, int] = {}
    for p in res.points:
        if not p.feasible:
            for r in p.reason_codes:
                reason_counts[r.value] = reason_counts.get(r.value, 0) + 1
    if reason_counts:
        w("Infeasible-point reasons: "
          + "; ".join(f"{k} x{v}" for k, v in sorted(reason_counts.items())) + ".")
        w("")
    w("**Mass note:** every mass value is *modeled component mass (incomplete Stage-1 "
      "accounting, 4.8a)* -- never total-system, launch, or flight mass.")
    w("")
    nonconv = [p for p in res.points if p.category is ts.PointCategory.NONCONVERGED]
    if nonconv:
        w("## Nonconvergence diagnostic (excluded from ranking)")
        w("")
        w("These points did **not** converge in the fixed-point solver. Nonconvergence is "
          "**not evidence of physical infeasibility** -- it may indicate a solver basin / "
          "step-tolerance limit at an extreme grid corner. They are excluded from every "
          "front and never ranked. (Full per-point data, incl. grid coordinates, is in the "
          "CSV.)")
        w("")
        w("| case | Q (W) | m_dot (kg/s) | A_plan (m^2) | P_lo (Pa) |")
        w("|---|---:|---:|---:|---:|")
        for p in nonconv:
            w(f"| {p.case_id} | {p.grid_heat_load_W:g} | {p.grid_mass_flow_kg_s:g} | "
              f"{p.grid_radiator_area_m2:g} | {p.grid_low_side_pressure_Pa:g} |")
        w("")
    w("## The six Pareto fronts")
    w("")
    for f in res.fronts:
        members = [p for p in res.points if f.name in p.pareto_fronts]
        w(f"### {f.name}")
        w("")
        w(f"- axes: **{f.x_axis}** ({f.x_sense}) vs **{f.y_axis}** ({f.y_sense})")
        w(f"- dominating assumption / active-constraint driver: {f.dominating_assumption}")
        w(f"- feasible points considered: {f.n_feasible}; non-dominated members: "
          f"{len(members)}{'  **[degenerate/empty: ' + f.note + ']**' if f.degenerate else ''}")
        if members:
            w("")
            w(f"| point_id | {f.x_axis} | {f.y_axis} | active constraint |")
            w("|---|---:|---:|---|")
            for p in sorted(members, key=lambda q: q.metrics[f.x_axis]):
                w(f"| `{p.point_id}` | {p.metrics[f.x_axis]:.3g} | {p.metrics[f.y_axis]:.3g} "
                  f"| {p.active_constraint} |")
        w("")
    w("## No single case is optimal on every front")
    w("")
    from collections import Counter
    fcount: Counter = Counter()
    for f in res.fronts:
        for cid in set(f.member_case_ids):
            fcount[cid] += 1
    max_fronts = max(fcount.values()) if fcount else 0
    w(f"No single case is Pareto-optimal on every named front: the most any case reaches is "
      f"**{max_fronts} of {len(res.fronts)}** fronts, and non-dominated membership is "
      f"distributed across **{len(fcount)} of {meta['n_cases']}** cases. This establishes "
      "multi-front trade-off diversity under this Stage-1 grid; it is **not** a global "
      "aggregate-ranking claim over the full objective vector.")
    w("")
    w("Fronts each case is Pareto-optimal on: "
      + "; ".join(f"{c} ({n}/{len(res.fronts)})" for c, n in sorted(fcount.items())) + ".")
    w("")

    md_path = Path("docs/trade-study-data.md")
    md_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {csv_path} ({len(res.points)} points) and {md_path} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
